"use client";
import { useState, type ReactNode } from "react";

// Detailed, interactive "OpenShell on Kubernetes" deployment. Click any object to see
// what it is, plus how THIS setup maps to it. Grouped by where things actually live:
// external clients, the openshell namespace (gateway + its state), the agent-sandbox
// controller, and the sandbox pods (in their own openshell-sandboxes namespace).

const NV = "#76b900", BLUE = "#6f8fd0", PURPLE = "#a78bfa", AMBER = "#e0a800",
      GREEN = "#34d399", SLATE = "#94a3b8", CYAN = "#22d3ee", RED = "#ef6b6b";

type N = { id: string; label: string; sub?: string; color: string; what: ReactNode; ours: ReactNode };

const NODES: Record<string, N> = {
  cli: { id: "cli", label: "CLI / SDK / TUI", sub: "openshell …", color: SLATE,
    what: <>The operator surface. <code>openshell gateway add</code>, <code>sandbox create</code>, <code>policy set</code>, <code>inference set</code>. Authenticates with an mTLS client cert + (optionally) an OIDC JWT.</>,
    ours: <>Installed on the VM and registered against the gateway over NodePort <code>30808</code> (no OIDC in this single-node setup).</> },
  oidc: { id: "oidc", label: "OIDC Identity Provider", sub: "Keycloak / Entra ID", color: AMBER,
    what: <>Issues JWTs with role claims so the gateway can do per-method authorization (admin vs read-only user).</>,
    ours: <>Keycloak <strong>is</strong> deployed (realm <code>openshell</code>) and gates the browser UIs — the console and Grafana via the Envoy ingress (OIDC SSO). The gateway itself still runs unauthenticated (<code>allowUnauthenticatedUsers</code>, dev) to avoid a boot-time issuer dependency, so the CLI works with no SSO.</> },
  grpcroute: { id: "grpcroute", label: "Service", sub: "NodePort :30808", color: BLUE,
    what: <>Inbound gRPC reaches the gateway through a Service (and, with Gateway API, a GRPCRoute on an Envoy Gateway for edge TLS + path routing).</>,
    ours: <>A plain Service exposed as NodePort <code>30808</code> so the in-VM shell and the <code>openshell</code> CLI can reach it. (No Envoy — that's an optional add-on.)</> },
  gw: { id: "gw", label: "Gateway", sub: "API · state · policy · inference", color: NV,
    what: <>The control plane. Serves the gRPC API, stores provider creds, delivers policy, hosts the inference router, and <strong>authenticates each sandbox's supervisor over mTLS</strong>.</>,
    ours: <>The <code>openshell</code> gateway (Helm chart) in namespace <code>openshell</code>. Its Kubernetes compute driver watches the Sandbox CRD on k3s.</> },
  pvc: { id: "pvc", label: "PVC", sub: "durable state", color: GREEN,
    what: <>Persists the gateway's SQLite DB (sandbox registry, policy revisions, provider config) across restarts.</>,
    ours: <>Bound via k3s's built-in <code>local-path</code> provisioner on the single node.</> },
  secrets: { id: "secrets", label: "Secrets", sub: "PKI + SSH handshake", color: RED,
    what: <>The gateway-minted sandbox-JWT signing keys + the mTLS PKI used for the supervisor handshake and exec/SSH relay.</>,
    ours: <>Generated by the <code>pkiInitJob</code> hook. We set <code>sandboxJwt.secretDefaultMode: 0444</code> so the random-UID gateway pod can read the signing key.</> },
  rbac: { id: "rbac", label: "RBAC", sub: "SA + Role bindings", color: PURPLE,
    what: <>The gateway + sandbox ServiceAccounts and their Roles — what the compute driver may do (create Sandboxes, read pods) and what each sandbox's SA may do.</>,
    ours: <>Plain Kubernetes RBAC on k3s. Pod-level isolation comes from the <code>gvisor</code> RuntimeClass + (optional) Kyverno admission policy.</> },
  pki: { id: "pki", label: "pkiInitJob", sub: "cert bootstrap", color: CYAN,
    what: <>A pre-install hook (<code>openshell-gateway generate-certs</code>) that creates the server + client mTLS Secrets in-cluster — or cert-manager Issuers for auto-rotation.</>,
    ours: <>The built-in <code>pkiInitJob</code> (no cert-manager) runs once at install on k3s.</> },
  ctrl: { id: "ctrl", label: "agent-sandbox controller", sub: "agents.x-k8s.io · CRDs", color: BLUE,
    what: <>The kubernetes-sigs/agent-sandbox operator. Reconciles each <code>Sandbox</code> CR into a Pod (+ PVC).</>,
    ours: <>Deployed by Ansible alongside the gateway; watches <code>sandboxes.agents.x-k8s.io</code> on the cluster.</> },
  pod: { id: "pod", label: "Sandbox Pod", sub: "supervisor + agent · gVisor", color: PURPLE,
    what: <>Each sandbox is a Pod with the <strong>supervisor</strong> (sideloaded init-container) wrapping the <strong>agent</strong> container (OpenClaw, or another agent). The supervisor dials the gateway over mTLS and enforces the L7 policy proxy.</>,
    ours: <>Created by <code>openshell sandbox create</code> in namespace <code>openshell-sandboxes</code> (separate from the gateway's <code>openshell</code>), on image <code>openclaw:latest</code>, pinned to <code>RuntimeClass: gvisor</code>.</> },
  guard: { id: "guard", label: "Network Guardrail + Privacy Router", sub: "egress + inference.local", color: AMBER,
    what: <>Every outbound connection is checked (deny-by-default, per-binary). The privacy router sends <code>inference.local</code> to a model proxy (LiteLLM), stripping creds + injecting the real key.</>,
    ours: <>Routes <code>inference.local</code> → LiteLLM (namespace <code>litellm</code>) → the upstream model API. The agent never holds the key.</> },
  addons: { id: "addons", label: "Cluster add-ons", sub: "Envoy · Keycloak · Kyverno · monitoring", color: SLATE,
    what: <>Envoy Gateway (Gateway API + GRPCRoute), Keycloak (OIDC SSO), Kyverno (admission guardrails), and a monitoring stack.</>,
    ours: <>Envoy Gateway, Keycloak, and the monitoring stack (Prometheus / Grafana / Loki / Alloy / Tempo) <strong>are</strong> deployed; Kyverno <code>require-gvisor</code> is on. Headlamp is not deployed.</> },
};

export function OpenShellOnK8s() {
  const [sel, setSel] = useState("gw");
  const a = NODES[sel];
  const Chip = ({ id, w }: { id: string; w?: string }) => {
    const n = NODES[id];
    return (
      <button onClick={() => setSel(id)} className={`rounded-lg border px-2.5 py-1.5 text-left transition ${w ?? "w-full"}`}
        style={{ borderColor: n.color, background: sel === id ? `${n.color}26` : "transparent",
                 boxShadow: sel === id ? `0 0 0 1px ${n.color}` : "none", opacity: sel === id ? 1 : 0.82 }}>
        <div className="text-[12px] font-semibold leading-tight" style={{ color: n.color }}>{n.label}</div>
        {n.sub && <div className="text-[9.5px] text-[var(--color-fg-mut)]">{n.sub}</div>}
      </button>
    );
  };
  const Box = ({ title, children }: { title: string; children: ReactNode }) => (
    <div className="rounded-lg border border-dashed border-[var(--color-line-2)] p-2">
      <div className="mb-1 text-[9px] font-bold uppercase tracking-wide text-[var(--color-fg-mut)]">{title}</div>
      {children}
    </div>
  );

  return (
    <figure className="my-6 rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)] p-4">
      <figcaption className="mb-3 text-sm text-[var(--color-fg-mut)]">OpenShell on Kubernetes — click any object (detail shows how <em>this</em> setup maps to it)</figcaption>
      <div className="grid gap-2 lg:grid-cols-[150px_1fr_140px]">
        {/* external clients */}
        <div className="flex flex-col gap-2">
          <Box title="clients"><div className="space-y-2"><Chip id="cli" /><Chip id="oidc" /></div></Box>
        </div>
        {/* the cluster */}
        <div className="rounded-xl border-2 p-2" style={{ borderColor: SLATE }}>
          <div className="mb-1 text-[10px] font-bold uppercase tracking-wide" style={{ color: SLATE }}>k3s cluster (single node)</div>
          <div className="rounded-lg border-2 p-2" style={{ borderColor: NV }}>
            <div className="mb-1 text-[10px] font-bold" style={{ color: NV }}>namespace: openshell</div>
            <div className="mb-2"><Chip id="grpcroute" /></div>
            <div className="mb-2"><Chip id="gw" /></div>
            <div className="grid grid-cols-4 gap-1.5"><Chip id="pvc" /><Chip id="secrets" /><Chip id="rbac" /><Chip id="pki" /></div>
          </div>
          <div className="mt-2"><Box title="agent-sandbox controller"><Chip id="ctrl" /></Box></div>
          <div className="mt-2 rounded-lg border-2 p-2" style={{ borderColor: PURPLE }}>
            <div className="mb-1 text-[10px] font-bold" style={{ color: PURPLE }}>namespace: openshell-sandboxes</div>
            <Chip id="pod" />
          </div>
          <div className="mt-2"><Chip id="guard" /></div>
        </div>
        {/* add-ons */}
        <div className="flex flex-col gap-2"><Box title="cluster add-ons"><Chip id="addons" /></Box></div>
      </div>
      <div className="mt-3 rounded-lg border border-[var(--color-line)] bg-[var(--color-bg-2)] p-4 text-sm text-[var(--color-fg-dim)]">
        <div className="mb-1 text-xs font-semibold" style={{ color: a.color }}>{a.label}</div>
        <div className="mb-2">{a.what}</div>
        <div className="rounded border-l-2 pl-2 text-[13px]" style={{ borderColor: NV }}>
          <span className="text-[10px] font-semibold uppercase" style={{ color: NV }}>in this setup&nbsp;</span>{a.ours}
        </div>
      </div>
    </figure>
  );
}
