// Shared pastel palette for the workshop's architecture diagrams (soft-pastel style,
// extended with Red Hat red + NVIDIA green). Brought over for SkillSupplyChain; other
// diagrams in this repo define their colors inline and are unaffected.
export const DIAGRAM = {
  font: "'Trebuchet MS', Verdana, 'Segoe UI', Helvetica, sans-serif",
  bg: "#f7f8fb",
  ink: "#3a3a4d",
  sub: "#5b5d70",
  border: "#b9bccd",
  lav: "#e9e5fb",
  blue: "#e7effb",
  gray: "#edeef2",
  data: "#e3f0ea",
  white: "#ffffff",
  enf: "#fde6c8",
  redTint: "#fde7e7",
  greenTint: "#eef6e0",
  auth: "#7c3aed",
  ctrl: "#5b6b7d",
  use: "#0e7490",
  create: "#e8730c",
  green: "#16a34a",
  red: "#dc2626",
  redhat: "#ee0000",
  nvidia: "#76b900",
} as const;
